### ISSUE TITLE
Touchup Requests Or Bugs

### ISSUE THREAD

**Issue by RinMaru** [SonicFreak94/sadx-fixed-edition#3]
I'm not sure if this qualifies for errors you're looking for so forgive my ignorance  plz

Your shadow does not appear on it but under it.
![00c796aa-0676-11e7-8ef0-34ca6195ac2e](https://cloud.githubusercontent.com/assets/15071652/23828271/1444942e-069b-11e7-9161-9f68481ec10f.PNG)``
Again your shadow should be prioritized over the texture.
![0a39c6e0-0676-11e7-8831-06e416ce043a](https://cloud.githubusercontent.com/assets/15071652/23828273/2870c79c-069b-11e7-8a86-a587a41c3ea5.PNG)
Another Shadow Fail.
![e10a5ad2-0675-11e7-9b6b-285fc1b13ed6](https://cloud.githubusercontent.com/assets/15071652/23828274/2d474d72-069b-11e7-8abf-e65bc01170d9.PNG)

**Comment by Zetchzie** [comment]
I just noticed this but the trees in Station Square where you fight Chaos 0 have no Collisions perhaps you can look at them?

**Comment by Zetchzie** [comment]
Another Collision issue in Station Square 

![capture](https://cloud.githubusercontent.com/assets/15071652/23841117/45326ade-0781-11e7-8a8c-8b8debc07e2a.PNG)

**Comment by michael-fadely** [comment]
It's hard to say what the issue is in the first screenshot without looking at the model, but the second one is an alpha sorting issue. The last one just looks like bad collision mesh.

As for the trees: they could be fixed (somewhat hackishly) by placing collision objects on top of them. While probably worth fixing just for the sake of polish, I consider it relatively low priority since it's not a blatant visual issue or something that affects gameplay in a particularly meaningful way.

**Comment by RinMaru** [comment]
Yea I can understand that. I was told to post these issues here since SADXFE is focused on fixing the game.

**Comment by Zetchzie** [comment]
Not sure what to do here but anytime you see these pads they just ignore you and you walk through them
![capture](https://cloud.githubusercontent.com/assets/15071652/23841326/c2404ef0-0782-11e7-86a5-68a583e5a410.PNG)

**Comment by RinMaru** [comment]
Egg Carrier texture warped its present in all versions

Left Side Warped
![ff33277a-086c-11e7-8d31-16b2c8401e50](https://cloud.githubusercontent.com/assets/15071652/23922865/94676b72-08da-11e7-857c-6db78ca7bbd0.PNG)
Right side How it should look
![0ebfe192-086d-11e7-9e8f-af9394cfd375](https://cloud.githubusercontent.com/assets/15071652/23922874/9fdd1876-08da-11e7-97e3-77513fcf066e.PNG)

**Comment by michael-fadely** [comment]
Nice find. I'm guessing that's the Sky Deck entrance.

**Comment by RinMaru** [comment]
yep also found some bending textures like in SS by the floating monitor
You had this fixed I think but Im using the DC textures
![capture](https://cloud.githubusercontent.com/assets/15071652/23924475/3c77f376-08e1-11e7-8e86-96ba8e3138fb.PNG)
Here it is happening here on both sides aswell
![capture2](https://cloud.githubusercontent.com/assets/15071652/23924516/5bb01f2a-08e1-11e7-9fa5-f600d0a35205.PNG)

**Comment by Zetchzie** [comment]
heres one im not sure how to explain this but bits of the ground at the very start of Red Mountain will overlap your shoes

its fine here
![capture](https://cloud.githubusercontent.com/assets/15071652/23924731/4574a6a8-08e2-11e7-8ec3-d521b19c361d.PNG)

venture a few steps and the ground texture rises it seems
![capture2](https://cloud.githubusercontent.com/assets/15071652/23924750/5ff50432-08e2-11e7-9602-402dd609acf4.PNG)

**Comment by RinMaru** [comment]
I think you've found this one previously too.
![capture](https://cloud.githubusercontent.com/assets/15071652/23924993/8d05cf5a-08e3-11e7-8ea7-d3d153217e3c.PNG)

more texture bending in the Train Station
![capture2](https://cloud.githubusercontent.com/assets/15071652/23925024/b615402e-08e3-11e7-8b80-fd1690b6df35.PNG)

**Comment by michael-fadely** [comment]
Well, the issue with those is that they're all in the Dreamcast models, so there's not much I can do there. I fixed DX's Red Mountain a long time ago.

**Comment by Zetchzie** [comment]
is there a way to get RED Mountains fix working with DC mods? the ground issue has always been there afaik the invisible plants are what i noticed you fixed

**Comment by supercoolsonic** [comment]
Alright, I'm gonna stop being annoying by posting Fixed Edition requests in PkR's DC mods area and actually submit some things here for once.

-The MT KUSA objects in Red Mountain, you know, the little grass things that you got the character check disabled for? Would it be possible to increase their draw distance? It's really easy to miss them. Also, they have a high-poly model that actually *animates*, but the camera has to be *really* close up to the grass, so it's unlikely that you'd ever see it.

-The spinning fans in Red Mountain. The switch between their low-poly and high-poly version is *so* noticeable.  Could that be improved?

-The bridge objects in Windy Valley. There are 4 types (1 is unused normally), and they all have this really awkward collision. I think it's because the breakable bridges are set to collapse as soon as the player touches it, but if it collapsed right away, then you'd have a real hard time getting that 1-up item box at the end of Act 1. So, it doesn't process collision with the player until you're about *halfway* across the bridge. But the model still reacts as if you're way back at the start of the bridge when it starts reacting. And the 2 bridge types that don't collapse *still* use this kind of behavior. If the collapsing bridges aren't able to be worked with, would it be possible to make the normal bridges act properly?

-There are several objects in Casinopolis that I'm confused about. First is object number 82, "Emergency". This thing is placed *all over* the Sonic Pinball table, and even the Nights table has a couple. But....nothing shows up in-game where it's placed. Nothing at all. I asked PkR to look at what it's even supposed to do, and he said there's coding to display a collision sphere when debug mode is activated, but...
![nothingness](https://cloud.githubusercontent.com/assets/26051785/24583933/c511af5e-1720-11e7-8828-0ce5a3d66329.png)
There's nothing there. I used a temporary layout file to view this, because normally collision blocks the view and obstructs seeing any other collision on the table. I removed that collision, but there's still nothing. Along the sides, next to the towers with the floating item boxes in them, and even up at the top of the towers themselves, this object is placed. ...But there's nothing there. PkR said it also might just be a collision object, but I don't see Sonic react to anything at all when he touches where one should be. Would it possible to look into this thing and figure out what it's really meant to do, and restore it?

-Still in Casinopolis, could object numbers 113 and 124 be investigated? SONZ and SMOKE? Both are unused objects, but I'm just curious as to what they're meant to do, because I can't make them do anything in-game. Nothing appears where they're placed.

-And then could 189 and 194 also be looked at? LETSGO and MUD? Just curious to what they are, and if using them correctly could restore something possibly.

-Two objects in Lost World, numbers 71 and 72, O Dou1 and O Dou2. What are these objects meant to do?

-Object number 82 in Red Mountain, O BLOW2. O BLOW is an invisible object that generates a quiet sound effect. It's placed in Act 2 for Sonic normally, but is outside of the level models and is placed too far away for it to be heard normally. ...What does O BLOW2 do? 

I'm aware these object investigation requests aren't exactly "fixes" per se, but I really don't know who else to turn to for these things. I have absolutely zip knowledge about how to actually go into the game and examine its coding, let alone looking at an object's coding. So, would you mind looking at them for me? Please?

-Object number 19 in Sky Chase, TARGET. What's it do?

-Object number 123 in Sky Deck, W WALL. Could you look at it?

-Lastly, object number 69 in Final Egg, O UP TARGET2. UP TARGET1 are the dolls that Gamma shoots in his level normally, but the second one is the same....but nothing pops out of it. However, it's used in his Act to plug a hole between the door to the left of where he starts and the ceiling. ...Surely this object can't exist just to *plug a hole*, right? Is there anything else it can do?

Okay, that's all the objects I'm curious about. I'd really, *really* appreciate it if you could look at them and tell me what they do, and how to make them do it, if anything at all.

-The stoplight objects in Station Square have an ability to rotate, but only its collision rotates if given rotation values. This results in exactly what happened originally with the item boxes. There's a problem with one in Super Sonic's layout of the Station area (Main Area) of Station square. The one closest to the boat can be walked through because it's technically rotated, but the model itself doesn't move. Could the rotation coding for the item boxes also be applied to this object?

-Can the underwater rippling effect seen on the Gamecube version be restored in the PC version?

-I guess...there's one more object I curious of. I wonder if the coding for that duck enemy in the Autodemo is still in the final. I know it's still in the object list, but it's coding has been redirected to the Egg Keeper.

-The Buyon enemy, the badnik that is exclusive to Twinkle Park. It has two behaviors, and one is really hard to see in normal gameplay. Usually, it bloats up its body and waddles toward you, but it also rarely stays deflated and hops around like a rabbit. Was this second behavior intended to be seen more often? ...Is there a way it can be seen more often? I know of one definite way to see it hop around. The first one Sonic comes across, right after the first bowling section: don't destroy it. Pass it, and continue on, but when you reach the hill leading to the small pond with a single Sweep badnik and an invincibility item box floating high above it, get on the slanted ledge and look down at it. You should be able to see it hop about. It's just that whenever you're near it, good luck trying to make it hop.

-PkR's restored Eggman Announcement voice clips in Act 2 of Sky Deck. They're cut off normally, and I heard it's because of a bug due to the game running at 60fps. But it's weird to me. Eggman's line of "Go up! Full speed ahead!" plays completely. Or, at least, *almost* completely. Yet the other one: "Descending into the clouds. Slow the ship down!" cuts off *super* early. Why is that?

-If Tails touches an air bubble, he'll use his drowning animation instead of his "got air bubble" animation. I believe he has a proper animation for this.... I *think* he does, but I'm not 100% sure.

-When going down the automated segment at the end of Windy Valley Act 3, if you have a shield, sometimes you'll run down the wall outside it.

-I know you were pursuing this since you first started SADXFE, but those orange things in Speed Highway Act 2 still don't effect Sonic at all.

-Several objects continue moving when the game is paused, like the clock in Speed Highway, some machinery in Sky Deck, and so on.

-Sometimes, when using the elevator switch between the interior and exterior on the Egg Carrier, the hatch will be closed and you'll get stuck, but the area will transition anyway.

-The ice patches in Ice Cap 2 are not normally visible in SADX, but they're there. I'm pretty sure they can be restored in vanilla SADX. Same for some pieces of the Reala pinball table in Casinopolis.

...And that's all I have at the moment. Thanks for taking the time to read this, and I hope we can work with each other to improve the game! Have a great night/day!

**Comment by RinMaru** [comment]
One area in Red mountain is still showing unleveled ground (the Secret area) the other area has been fixed in DC Mods but this area remains bugged
![20170507150936_1](https://cloud.githubusercontent.com/assets/15071652/25785423/d75a22c4-334d-11e7-94a6-16765c8a2920.jpg)

If you skip tails cutscene "In Tails story" after being rescud your camera will get stuck behind the bulding
![20170507155137_1](https://cloud.githubusercontent.com/assets/15071652/25785432/0bbccf80-334e-11e7-8c65-7208427b1069.jpg)

this area should be dark as the rest of the ground around it but it ignores the lighting
![20170507162849_1](https://cloud.githubusercontent.com/assets/15071652/25785439/3a0d3e24-334e-11e7-8f36-63957f45e88e.jpg)

Should that area really look like that? _Possible PL Mod stuff_
![20170507165752_1](https://cloud.githubusercontent.com/assets/15071652/25785442/5e5619b8-334e-11e7-94a3-2ebefad396c3.jpg)

Bigs Fishing line will dissapear when in widescreen
![20170507173429_1](https://cloud.githubusercontent.com/assets/15071652/25785443/73a34278-334e-11e7-8800-ee7ba3fef9c4.jpg)

Fencing is fighting with the stairs
![20170507201640_1](https://cloud.githubusercontent.com/assets/15071652/25787144/dd72d2cc-336c-11e7-8854-6376430c908b.jpg)

Is this supposed to happen a visible seam here but only at a certain angle/ not really. you can find it if you look at it
![20170507224348_1](https://cloud.githubusercontent.com/assets/15071652/25788449/20b66bb6-3377-11e7-9248-c8ba4164bc4e.jpg)

If you skip E-102s cutscene (E-102s story) where he must retrieve the bird from amy in the cell room the camera will be set behind scenery until you move
